// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-y3QSdrvH5PLtQkrHZE3LjRtk97f0hs',
    appId: '1:186128623949:web:6ef23f723bc3727386af04',
    messagingSenderId: '186128623949',
    projectId: 'habit-ccd80',
    authDomain: 'habit-ccd80.firebaseapp.com',
    storageBucket: 'habit-ccd80.firebasestorage.app',
    measurementId: 'G-YCW6P55ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaySbdvEGq0XEX6KmyykARnUgmcSjjIE',
    appId: '1:186128623949:android:e38e0a51fd8c49d386af04',
    messagingSenderId: '186128623949',
    projectId: 'habit-ccd80',
    storageBucket: 'habit-ccd80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ9uzHX06mIXLcbIp2ctYeIiKuAAR4LoY',
    appId: '1:186128623949:ios:eb70634481fcb62f86af04',
    messagingSenderId: '186128623949',
    projectId: 'habit-ccd80',
    storageBucket: 'habit-ccd80.firebasestorage.app',
    iosBundleId: 'com.example.habitSpeedCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ9uzHX06mIXLcbIp2ctYeIiKuAAR4LoY',
    appId: '1:186128623949:ios:eb70634481fcb62f86af04',
    messagingSenderId: '186128623949',
    projectId: 'habit-ccd80',
    storageBucket: 'habit-ccd80.firebasestorage.app',
    iosBundleId: 'com.example.habitSpeedCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ-y3QSdrvH5PLtQkrHZE3LjRtk97f0hs',
    appId: '1:186128623949:web:312fe28b303ab44386af04',
    messagingSenderId: '186128623949',
    projectId: 'habit-ccd80',
    authDomain: 'habit-ccd80.firebaseapp.com',
    storageBucket: 'habit-ccd80.firebasestorage.app',
    measurementId: 'G-GNSQ1JQFMJ',
  );
}

